### ISSUE TITLE
Routing Peers Stats Page - math errors? 

### ISSUE THREAD

**Issue by manakill** [Ride-The-Lightning/RTL#212] opened 2019-12-25 21:31 UTC
**Describe the bug**
Routing peers stats show wrong sums on different time frames 

**To Reproduce**
1. Go to '...' RTL
2. Click on '....'. Routing peers 
3. Change to 1 month time frame and note totals. Change to 1 week and note totals. 

**Expected behavior**
I expect more events in the long time frame. 

**Actual behavior**
Wrong math displays 

**Screenshots**
**1 month : notice JustLearnBitcoin has 1 
![2019-12-25 16 24 13](https://user-images.githubusercontent.com/9597295/71450625-1c4f5d00-2733-11ea-9ac9-0ab3469c5e1b.jpg)

**1 week time frame : notice more than 1 on JustLearnBitcoin - the 1 month time frame should be totalling more than 1 week 
![2019-12-25 16 27 28](https://user-images.githubusercontent.com/9597295/71450644-7c460380-2733-11ea-93c8-8bab8c0d62ae.jpg)

**Your environment**
* version of `lnd` - 8.1
* operating system (`uname -a` on *Nix)- nodl Linux 
* version of `btcd`, `bitcoind`, or other backend
Bitcoind 180100
* any other relevant environment details

**Additional context**

**Comment by ShahanaFarooqui** [comment] 2019-12-29 23:31
@manakill we tried with different nodes and durations but we were unable to reproduce this error. Please share your RTL logs.

**Comment by manakill** [comment] 2019-12-31 14:55
Where would I find them? I see files in /opt/bitcoin/rtl  but no logs anywhere. Extraction/download file from GUI would be handy.

**Comment by ShahanaFarooqui** [comment] 2019-12-31 15:20
@manakill you can either find them at their default location which is ..../rtl/logs. If you do not have that folder then your logs might be turned off. In that case, you need to turn them on in rtl config file, restart the server and run the same searches in your routing peers page one more time. This time, you will be able to find the logs in ../rtl/logs folder.

**Comment by manakill** [comment] 2020-01-01 15:11
logs
[RTL.log](https://github.com/Ride-The-Lightning/RTL/files/4014183/RTL.log)

**Comment by ShahanaFarooqui** [comment] 2020-01-02 17:30
@manakill, after comparing your shared logs, it looks like LND is not sending the expected response for your queries. 

To confirm, we can compare rtl.log's data from line 129 and line 132. First query is to get approx. a week's history and second is for a month. Within 1 week, channel "669379380597882881" has been used 12 times to send outbound payments but the monthly result only shows 1 event for the same. We can see differences between almost, all event totals. 

Please feel free to open an issue with LND (this issue link can be shared for more details), as the UI will process and show the data based upon the LNP responses only.

Below is the reference data from your log, after removing irrelavant information:

Line 129 (Dec/24/2019 5:00:00 AM till Jan/1/2020 3:06:35 PM): 
{
	"forwarding_events": [
		{
			"timestamp": "1577795429",
			"chan_id_in": "669956624142630913",
			"chan_id_out": "669379380597882881",
		},
		{
			"timestamp": "1577779753",
			"chan_id_in": "669956624142630913",
			"chan_id_out": "669379380597882881",
		},
		{
			"timestamp": "1577779297",
			"chan_id_in": "669956624142630913",
			"chan_id_out": "669989609599598593",
		},
		{
			"timestamp": "1577776086",
			"chan_id_in": "669379380597882881",
			"chan_id_out": "669989609599598593",
		},
		{
			"timestamp": "1577775415",
			"chan_id_in": "669956624142630913",
			"chan_id_out": "669989609599598593",
		},
		{
			"timestamp": "1577727289",
			"chan_id_in": "669379380597882881",
			"chan_id_out": "669956624142630913",
		},
		{
			"timestamp": "1577654388",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "670990165109047296",
		},
		{
			"timestamp": "1577653255",
			"chan_id_in": "669956624142630913",
			"chan_id_out": "661302368152125441",
		},
		{
			"timestamp": "1577644531",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "670990165109047296",
		},
		{
			"timestamp": "1577642742",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "670990165109047296",
		},
		{
			"timestamp": "1577634646",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "670990165109047296",
		},
		{
			"timestamp": "1577625742",
			"chan_id_in": "669956624142630913",
			"chan_id_out": "669379380597882881",
		},
		{
			"timestamp": "1577625582",
			"chan_id_in": "669956624142630913",
			"chan_id_out": "669379380597882881",
		},
		{
			"timestamp": "1577625330",
			"chan_id_in": "669956624142630913",
			"chan_id_out": "669379380597882881",
		},
		{
			"timestamp": "1577624907",
			"chan_id_in": "618183920081960960",
			"chan_id_out": "669379380597882881",
		},
		{
			"timestamp": "1577623787",
			"chan_id_in": "669956624142630913",
			"chan_id_out": "669379380597882881",
		},
		{
			"timestamp": "1577623561",
			"chan_id_in": "669956624142630913",
			"chan_id_out": "669379380597882881",
		},
		{
			"timestamp": "1577623326",
			"chan_id_in": "669956624142630913",
			"chan_id_out": "669379380597882881",
		},
		{
			"timestamp": "1577622729",
			"chan_id_in": "669956624142630913",
			"chan_id_out": "669379380597882881",
		},
		{
			"timestamp": "1577608745",
			"chan_id_in": "669956624142630913",
			"chan_id_out": "617827678445174784",
		},
		{
			"timestamp": "1577608399",
			"chan_id_in": "669956624142630913",
			"chan_id_out": "617827678445174784",
		},
		{
			"timestamp": "1577608096",
			"chan_id_in": "669956624142630913",
			"chan_id_out": "617827678445174784",
		},
		{
			"timestamp": "1577591085",
			"chan_id_in": "618183920081960960",
			"chan_id_out": "617827678445174784",
		},
		{
			"timestamp": "1577575926",
			"chan_id_in": "669379380597882881",
			"chan_id_out": "669808190067179521",
		},
		{
			"timestamp": "1577440700",
			"chan_id_in": "617827678445174784",
			"chan_id_out": "669956624142630913",
		},
		{
			"timestamp": "1577438554",
			"chan_id_in": "669379380597882881",
			"chan_id_out": "670265587004997633",
		},
		{
			"timestamp": "1577405044",
			"chan_id_in": "669379380597882881",
			"chan_id_out": "670265587004997633",
		},
		{
			"timestamp": "1577405028",
			"chan_id_in": "669379380597882881",
			"chan_id_out": "670265587004997633",
		},
		{
			"timestamp": "1577402512",
			"chan_id_in": "669379380597882881",
			"chan_id_out": "661302368152125441",
		},
		{
			"timestamp": "1577402492",
			"chan_id_in": "669379380597882881",
			"chan_id_out": "670265587004997633",
		},
		{
			"timestamp": "1577402486",
			"chan_id_in": "669379380597882881",
			"chan_id_out": "670265587004997633",
		},
		{
			"timestamp": "1577402215",
			"chan_id_in": "669379380597882881",
			"chan_id_out": "670265587004997633",
		},
		{
			"timestamp": "1577195997",
			"chan_id_in": "618324657616846848",
			"chan_id_out": "669956624142630913",
		},
		{
			"timestamp": "1577186010",
			"chan_id_in": "669379380597882881",
			"chan_id_out": "669808190067179521",
		},
		{
			"timestamp": "1577185773",
			"chan_id_in": "669379380597882881",
			"chan_id_out": "669808190067179521",
		},
		{
			"timestamp": "1577179697",
			"chan_id_in": "669808190067179521",
			"chan_id_out": "661633321095659521",
		},
		{
			"timestamp": "1577179691",
			"chan_id_in": "669808190067179521",
			"chan_id_out": "661633321095659521",
		},
		{
			"timestamp": "1577179686",
			"chan_id_in": "669808190067179521",
			"chan_id_out": "661633321095659521",
		}
	],
	"last_offset_index": 38
}
===============================================================================
Line 132 (Dec/3/2019 5:00:00AM till Jan/1/2020 3:06:35 PM): 
{
	"forwarding_events": [
		{
			"timestamp": "1577008354",
			"chan_id_in": "617827678445174784",
			"chan_id_out": "669438754281095169",
		},
		{
			"timestamp": "1577008350",
			"chan_id_in": "617827678445174784",
			"chan_id_out": "669438754281095169",
		},
		{
			"timestamp": "1577008128",
			"chan_id_in": "617827678445174784",
			"chan_id_out": "669438754281095169",
		},
		{
			"timestamp": "1577007729",
			"chan_id_in": "617827678445174784",
			"chan_id_out": "669438754281095169",
		},
		{
			"timestamp": "1577007710",
			"chan_id_in": "617827678445174784",
			"chan_id_out": "669438754281095169",
		},
		{
			"timestamp": "1576991183",
			"chan_id_in": "617827678445174784",
			"chan_id_out": "669438754281095169",
		},
		{
			"timestamp": "1576991174",
			"chan_id_in": "617827678445174784",
			"chan_id_out": "669438754281095169",
		},
		{
			"timestamp": "1576978544",
			"chan_id_in": "669379380597882881",
			"chan_id_out": "669808190067179521",
		},
		{
			"timestamp": "1576962071",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "669634467277438977",
		},
		{
			"timestamp": "1576961342",
			"chan_id_in": "669634467277438977",
			"chan_id_out": "669379380597882881",
		},
		{
			"timestamp": "1576888731",
			"chan_id_in": "668348038641745921",
			"chan_id_out": "669438754281095169",
		},
		{
			"timestamp": "1576873617",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576702512",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576657046",
			"chan_id_in": "668348038641745921",
			"chan_id_out": "643759660145311744",
		},
		{
			"timestamp": "1576649009",
			"chan_id_in": "617818882218196993",
			"chan_id_out": "618183920081960960",
		},
		{
			"timestamp": "1576613812",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576613416",
			"chan_id_in": "618183920081960960",
			"chan_id_out": "627310966089580545",
		},
		{
			"timestamp": "1576587827",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576587656",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576587547",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576587525",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576549248",
			"chan_id_in": "617818882218196993",
			"chan_id_out": "618183920081960960",
		},
		{
			"timestamp": "1576519930",
			"chan_id_in": "617827678445174784",
			"chan_id_out": "618455499420008448",
		},
		{
			"timestamp": "1576519697",
			"chan_id_in": "617827678445174784",
			"chan_id_out": "661633321095659521",
		},
		{
			"timestamp": "1576501352",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576465505",
			"chan_id_in": "618183920081960960",
			"chan_id_out": "668348038641745921",
		},
		{
			"timestamp": "1576464101",
			"chan_id_in": "617818882218196993",
			"chan_id_out": "618183920081960960",
		},
		{
			"timestamp": "1576460785",
			"chan_id_in": "618183920081960960",
			"chan_id_out": "626899748729716736",
		},
		{
			"timestamp": "1576459176",
			"chan_id_in": "617818882218196993",
			"chan_id_out": "618183920081960960",
		},
		{
			"timestamp": "1576458590",
			"chan_id_in": "618183920081960960",
			"chan_id_out": "623647393437581312",
		},
		{
			"timestamp": "1576432937",
			"chan_id_in": "617818882218196993",
			"chan_id_out": "617827678445174784",
		},
		{
			"timestamp": "1576353641",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576353613",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576345454",
			"chan_id_in": "617818882218196993",
			"chan_id_out": "617827678445174784",
		},
		{
			"timestamp": "1576341898",
			"chan_id_in": "617818882218196993",
			"chan_id_out": "617827678445174784",
		},
		{
			"timestamp": "1576310071",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617827678445174784",
		},
		{
			"timestamp": "1576310064",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617827678445174784",
		},
		{
			"timestamp": "1576293334",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576275765",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576275744",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576209428",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576207745",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576207573",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576207256",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576207189",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576207125",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576206652",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576202441",
			"chan_id_in": "617827678445174784",
			"chan_id_out": "661311164239052801",
		},
		{
			"timestamp": "1576201882",
			"chan_id_in": "617827678445174784",
			"chan_id_out": "618022292020789248",
		},
		{
			"timestamp": "1576193974",
			"chan_id_in": "617827678445174784",
			"chan_id_out": "618183920081960960",
		},
		{
			"timestamp": "1576190401",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576190324",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576181927",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "620080577706786816",
		},
		{
			"timestamp": "1576174773",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576173898",
			"chan_id_in": "617818882218196993",
			"chan_id_out": "618183920081960960",
		},
		{
			"timestamp": "1576159389",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576149038",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576108567",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576084867",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576039440",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576020928",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576020800",
			"chan_id_in": "617818882218196993",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576004552",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576004539",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1576002453",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1575974272",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1575941560",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1575921018",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1575914750",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1575914586",
			"chan_id_in": "661315562240278529",
			"chan_id_out": "621949747543015424",
		},
		{
			"timestamp": "1575908574",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617827678445174784",
		},
		{
			"timestamp": "1575890187",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1575886898",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1575886516",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1575880025",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1575872105",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1575859579",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1575764185",
			"chan_id_in": "617827678445174784",
			"chan_id_out": "618183920081960960",
		},
		{
			"timestamp": "1575764025",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "618183920081960960",
		},
		{
			"timestamp": "1575764005",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "618183920081960960",
		},
		{
			"timestamp": "1575751891",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1575751302",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1575751264",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1575751138",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1575748056",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1575729549",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1575722609",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1575709597",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1575673396",
			"chan_id_in": "617827678445174784",
			"chan_id_out": "661311164243771392",
		},
		{
			"timestamp": "1575656489",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1575616866",
			"chan_id_in": "617959619837231104",
			"chan_id_out": "639629894393659392",
		},
		{
			"timestamp": "1575572074",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1575540431",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1575492006",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1575481047",
			"chan_id_in": "617818882218196993",
			"chan_id_out": "617959619837231104",
		},
		{
			"timestamp": "1575465120",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1575411491",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1575406703",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1575405083",
			"chan_id_in": "661302368152125441",
			"chan_id_out": "617593482405150720",
		},
		{
			"timestamp": "1575350628",
			"chan_id_in": "617959619837231104",
			"chan_id_out": "618146536787017728",
		}
	],
	"last_offset_index": 100
}

**Comment by carlaKC** [comment] 2020-01-06 07:00
On first look at this, I think that the issue is emerging because the `ForwardingHistory` response is paginated. By default, we only return the first 100 forwarding events (which looks like it's the case for the month query).

If RTL is querying `ForwardingHistory` once off, this will be the reason that the month query does not have a full set of events. Does this sound right? I'm no js wizard unfortunately but I think that could be the case from a brief look at the code? 

If the nodes you tried to reproduce on had < 100 forwards in a month, they would not hit this bug. I'll try to reproduce this my side to confirm  :) 

If this is the case, the fix would be to repetitively query `ForwardingHistory`  until `last_offset_index` < `num_max_events`, which indicates that the full set of events has been retrieved. 

You can also increase the number of events you get per response application side by setting `num_max_events` in your request (although you'll always have to check pagination in case your query period hits that max).

**Comment by ShahanaFarooqui** [comment] 2020-01-06 23:06
@manakill, thanks again for bringing the issue into our attension and your patiance. 

For now, we have decided to resolve the issue by increasing the maximum number of events upto 1000. For summarized views, we will either request LND to provide separate API in distant future or will send repeated API calls according to future requirement.

Please feel free to pull the code from 'master' for the fix or 'UX' branch for our new UX alpha testing version. Or you can wait for our official release for updated UX version by the end of this week. We are closing this issue now. 

@carlaKC, Thanks for the quick response but it will be great if we can find this information in the REST documentation itself. Otherwise, other UI devs also might stumble on the same kind of issues. Please let us know if you need us to open an issue for documentation update.

**Closed by ShahanaFarooqui** 2020-01-06 23:06 UTC
Labels: bug

**Comment by carlaKC** [comment] 2020-01-07 19:07
No problem @ShahanaFarooqui :) 

I think that the [current documentation](https://api.lightning.community/#forwardinghistory) is alright in this specific case? If you think the wording could more explicitly refer to pagination please do open an issue. In general we could definitely be better in that department.

I really enjoyed exploring RTL to replicate this issue. Really awesome project 🚀

**Comment by ShahanaFarooqui** [comment] 2020-01-07 19:18
@carlaKC Thanks a lot for the feedback. These feedbacks motivate us to keep working :).

We are not connecting to LND through grpc but through REST APIs. Though, LND's documantation is much better than other LNP but it still has some scope of improvement. '[Switch](https://api.lightning.community/rest/index.html#post-v1-switch)' API states that, "The response will carry at most 50k records between the start time and the end time.", when the maximum limit is 100 record only.

**Comment by carlaKC** [comment] 2020-01-07 20:08
It has a maximum of 50k records because of the size limit that we place on queries. The default event count is 100, but you can set `num_max_events` to change that value. That warning is just there for cases where people set `num_max_events`>50k, because they will be limited by space restrictions, so we will only return 50k events.

For your use case, you can just set a sane `num_max_events` and then repetitively query. If you don't want to make a big change, you can maybe also pop the user a warning in the meantime `last_index_offset` = `max_num_events` to inform the user that they're not seeing everything (and to decrease their date range to see all) until you have repetitive queries implemented.

Hope that's helpful. If there's some rewording that would be useful in the docs I'd say the best course is to open an issue :)
