### ISSUE TITLE
Enable Child-Pays-For-Parent for on-chain transactions excluding 'sweep' transactions

### ISSUE THREAD

**Issue by hieblmi** [Ride-The-Lightning/RTL#720] opened 2021-06-22 15:58 UTC
**Is your feature request related to a problem? Please describe.**
In my particular case I looped out funds but set the max. fee increases for RBF/CFPF that the loop service can apply to the sweep transaction too low to be confirmed at this particular mempool period. Hence the loop service's sweep transaction is stuck in the mempool.

For reference: https://blog.lightning.engineering/technical/posts/2019/04/15/loop-out-in-depth.html
![image](https://user-images.githubusercontent.com/18631614/122960522-7e514880-d351-11eb-8097-969461b86f1a.png)

**Describe the solution you'd like**
For this use-case and more generally I think it would be nice to have a  CFPF action in the on-chain transaction section.
![image](https://user-images.githubusercontent.com/18631614/122957741-3aaa0f00-d350-11eb-847f-56a2d54ddb1f.png)

**Describe alternatives you've considered**
There are currently no alternatives in RTL to bump a fee manually.

**Comment by saubyk** [comment] 2021-06-26 17:19
Hi @hieblmi this feature if made available, has a potential to create a lot of confusion for the user, who may not be super advanced in their understanding of how Bitcoin transactions work especially in case of Loop's sweep's transaction. Because Loop service is also trying to RBF the sweep transactions and it can compete with user trying to CPFP manually.

I'll try to layout a scenario:
1. Sweep transaction appears as unconfirmed in RTL
2. User attempts to CPFP the unconfirmed transaction and the whole transaction is waiting to be confirmed
3. Loop service RBF's the original sweep and gets picked up in the block, while the above CPFP is still waiting. The CPFP is eventually rejected because now the original UTXO is spent

We should get @alexbosworth to weigh in, if it will be a good idea to enable user to intervene manually for onchain Loop out sweeps.

**Comment by alexbosworth** [comment] 2021-06-26 17:25
I think you described it accurately

The sweep should be identifiable though in various ways if you want to remove the ability to CPFP it, CPFPing the sweep is not recommended since you'll pay for more vbytes than if you simply RBF it, if you'd like to influence the RBF process in Loop you could create a feature request on that. You could also just use the server API and allow fine control over RBF yourself

**Comment by hieblmi** [comment] 2021-06-28 11:34
@saubyk Thank you for describing a scenario where CPFP in combination with Loop's RBF policy could lead to confusion. It makes sense. @alexbosworth I'll raise a feature request to possibly allow to raise the fee limit to which it is initially set when the swap in Lighting Terminal is initiated.

**Comment by saubyk** [comment] 2024-05-14 00:43
This requirement can be addressed by creating an exception for transactions which have labels `sweep` in it.

Any transactions with such labels shouldn't have CPFP enabled.

Although this is a weak protection, as the user can always edit the labels in the UI and then force the sweep anyway. But if the user does such things, they should also be ready for any unforeseen consequences of such action, which will not be under our control.

**Comment by ShahanaFarooqui** [comment] 2024-05-15 01:49
Closing with PR #1394.

**Closed by ShahanaFarooqui** 2024-05-15 01:49 UTC
Labels: enhancement, LND, CPFP
