### ISSUE TITLE
RTL on RaspiBlitz in hybrid mode creates a blank preview of invoice

### ISSUE THREAD

**Issue by PegasusNZ** [Ride-The-Lightning/RTL#1019] opened 2022-05-13 03:39 UTC
Create an invoice with title , amount and expiry time. The screen moves to what I would think is the approval screen the area which I expect would have a QRcode is displaying N/A and invoice date is 1970 everything else is blank? 
The invoice appears in the transaction list correctly

LND
0.12.1 beta
Raspiblitz 1.7.2

**Comment by saubyk** [comment] 2022-08-14 19:02
Hi @PegasusNZ looking at this issue now.

I am not aware about Raspiblitz hybrid mode. Can you please explain what that is?

I am running RTL on the latest version of LND and I am able to generate invoice just fine.

**Comment by cutiful** [comment] 2022-08-26 02:51
I have the same issue, but without RaspiBlitz. When the component is initialized, it receives the correct invoice object. Then it tries to find it in the list of invoices and fails (at that moment, the new invoice isn't in the list yet) and overrides it with `undefined`:
https://github.com/Ride-The-Lightning/RTL/blob/89e7ebadaa652845779934dd6e0848c8d1842a7e/src/app/lnd/transactions/invoice-information-modal/invoice-information.component.ts#L60-L62
Looks like a race condition?

**Comment by ShahanaFarooqui** [comment] 2022-09-22 00:25
@PegasusNZ & @cutiful Thank yo for the issue and inputs.

I was unable to reproduce it on my end but updated the code with assumptions of race condition. The fix will be released with v0.13.2. Closing this issue with PR #1104 but please feel free to comment if issue persists with >.0.13.2.

**Closed by ShahanaFarooqui** 2022-09-22 00:25 UTC
Labels: bug, LND
