### ISSUE TITLE
Opened channel with wrong peer

### ISSUE THREAD

**Issue by AnthonyRonning** [Ride-The-Lightning/RTL#499] opened 2020-09-30 14:38 UTC
**Describe the bug**
I can't reproduce it nor do I want to try but I went through the add peer -> add channel flow and when I added the new peer and clicked on button to add channel with the newly added peer, it opened a channel with a different peer I already had a channel with. 

If I had gone through the normal add channel with existing peer process I may have thought I screwed it up myself but I did have the newly added peer in my peer list, but channel with someone else. 

**To Reproduce**
1. Go to Channels
2. Click on Peers
3. Click on add peer
4. Add a peer
5. Do the optional "add channel with peer" afterwards
6. Channel opens with wrong peer

**Your environment**
* Version of `RTL` 0.8.1
* Version of `lnd` 0.10.4
* Version of `bitcoind` 0.20.1
* Browser & browser version: firefox 81
* Operating system (`uname -a` on *Nix) raspiblitz

**Comment by ShahanaFarooqui** [comment] 2020-10-05 18:36
@AnthonyRonning I failed to reproduce the error in multiple attempts on v0.8.1 as well as other versions. Can you please provide axact steps to reproduce the issue because RTL logs will also be unable to explain this strange behavior?

**Comment by AnthonyRonning** [comment] 2020-10-05 18:40
I had tried multiple times before this attempt and they all worked just fine too. Unsure of how it happened any differently than what I remember going through on the reproduction steps. It's also entirely possible I did something weird or misremembered it. But if you're unable to reproduce then maybe it can be closed, thanks for looking anyways.

**Comment by ShahanaFarooqui** [comment] 2020-10-05 18:42
@AnthonyRonning Thanks for the quick response. We are closing the issue for now. Please feel free to reopen if it happens again.

**Closed by ShahanaFarooqui** 2020-10-05 18:42 UTC
Labels: LND, troubleshooting
