### ISSUE TITLE
Eclair 0.6.2 breaks channel management

### ISSUE THREAD

**Issue by NCrashed** [Ride-The-Lightning/RTL#831] opened 2021-10-10 13:56 UTC
**Describe the bug**
The new release of Eclair 0.6.2 changes the API for channel management. Update fee operation doesn't work. The fee reported by each channel is now a duplication of the first channel in the list of all channels.

**To Reproduce**
1. Go to the channels tab and change the fee on a channel.
2. Get the error.
3. Check reported fee for all channels, all are the same and don't correspond with real values.

**Screenshots**
![image](https://user-images.githubusercontent.com/2116167/136698666-88c7de06-32ad-4a47-9be7-860c62a5fd26.png)

**Your environment**
* RTL: cf66708
* Eclair: 0.6.2

**Additional context**
The problem doesn't reproduce on 0.6.1.

Log:
```
Oct 10 13:47:09 main rtl-start[23389]: [2021-10-10T13:47:09.201Z] ERROR: Channels => Update Relay Fee Error: {"name":"StatusCodeError","statusCode":400,"message":"400 - {\"error\":\"The form field 'nodeId(s)' was malformed:\\nMust specify nodeId or nodeIds (but not both)\"}","error":{"error":"The form field 'nodeId(s)' was malformed:\nMust specify nodeId or nodeIds (but not both)"},"options":{"url":"http://localhost:3032/updaterelayfee","rejectUnauthorized":false,"json":true,"headers":{},"method":"POST","qs":{},"form":{"feeBaseMsat":"0","feeProportionalMillionths":"400","channelId":"103f2b2d9241527fc73948f27ad8cb3414679492a9ff6ae7d25a00923fb3c7ae"},"simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false},"response":{"statusCode":400,"body":{"error":"The form field 'nodeId(s)' was malformed:\nMust specify nodeId or nodeIds (but not both)"},"headers":{"access-control-allow-headers":"Content-Type, Authorization","access-control-allow-methods":"POST","cache-control":"public, no-store, max-age=0","server":"akka-http/10.2.4","date":"Sun, 10 Oct 2021 13:47:09 GMT","connection":"close","content-type":"application/json","content-length":"106"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"localhost:3032","port":"3032","hostname":"localhost","hash":null,"search":null,"query":null,"pathname":"/updaterelayfee","path":"/updaterelayfee","href":"http://localhost:3032/updaterelayfee"},"method":"POST","headers":{"content-type":"application/x-www-form-urlencoded","accept":"application/json","content-length":118}}}}
```

**Comment by viaj3ro** [comment] 2021-11-18 09:44
There was also a bug where RTL wasn't able to properly handle 0 base fee.
If a channel had 0 base fee, Updating the fee would automatically override the 0 base fee of with 1000 instead.
Would be good to make sure, this bug isn't replicated in the new update mechanism.

**Comment by ShahanaFarooqui** [comment] 2021-11-24 16:58
Duplicate of https://github.com/Ride-The-Lightning/RTL/issues/830

**Comment by ShahanaFarooqui** [comment] 2021-11-24 18:25
> There was also a bug where RTL wasn't able to properly handle 0 base fee. If a channel had 0 base fee, Updating the fee would automatically override the 0 base fee with 1000 instead. Would be good to make sure, this bug isn't replicated in the new update mechanism.

This is also fixed. The base fee was getting updated via the API but it was shown as 1000 in the UI.

**Closed by ShahanaFarooqui** 2021-11-24 18:25 UTC
Labels: bug, duplicate, Eclair, version compatibility
