### ISSUE TITLE
Problem with npm installing v0.12.2 updating from v.0.11.2 (On ubuntu server)

### ISSUE THREAD

**Issue by MysterX83** [Ride-The-Lightning/RTL#984] opened 2022-03-30 09:06 UTC
When i try to update from RTL v0.11.2 to v0.12.2 i run to the following issue: 

Here are my steps:
1. When i try to checkout v.0.12.2 and package-lock.json is changed (is changed by npm install v.0.11.2)
2. I fixed this with a git reset --hard
3. then checkout with: git checkout v0.12.2
4. then i run: npm install --only=prod
5. The following error occur:

../RTL/node_modules/@angular/compiler-cli/bundles/ngcc/main-ngcc.js:3
      import {createRequire as __cjsCompatRequire} from 'module';
             ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

Is this something i can fix myself? or is this a bug? And why is package-lock.json changed, should this be added to the .ignore file?

**Comment by ShahanaFarooqui** [comment] 2022-03-30 10:09
- What is your NodeJS and npm version?
- Package-lock is updated intentionally and it should not be ignored. Rather new updates should be installed through it.
- I believe that something went wrong in reset and checkout process. Most probably, you need to delete node_modules folder and run npm install —prod after that. 
- it is not a bug in RTL and the dependency issue can only be fixed locally.

**Comment by MysterX83** [comment] 2022-03-30 10:27
- NodeJS: v10.19.0,  NPM: v7.19.0
- I see that package-lock is updated intentionally but why checking back in the repo then? If you need this file initially why not creating it by installing? (i'm no expert so maybe this isn't possible ;-) )
- I can try your suggestion, thanks for that. 
- Ok thanks for the info.

**Comment by ShahanaFarooqui** [comment] 2022-03-30 11:45
NodeJS v>12 is required to run this project. Closing the issue now. Thanks.

**Closed by ShahanaFarooqui** 2022-03-30 11:45 UTC
