### ISSUE TITLE
Channel relay fee update not working anymore with eclair and latest 0.12.2

### ISSUE THREAD

**Issue by viaj3ro** [Ride-The-Lightning/RTL#978] opened 2022-03-17 09:57 UTC
somehow updating the channel relay fee randomly works and randomly it doesn't. So far no rule or order to it. When it doesn't work, clicking on `update` after changing the fee, just doesn't do anything... the popup window just stays open:

![image](https://user-images.githubusercontent.com/42124006/158784548-b804a545-d4de-4971-bcec-4e5cc44adff3.png)

restarting everything, didn't help.

**Comment by ShahanaFarooqui** [comment] 2022-04-18 17:06
@viaj3ro I tested it in RTL v0.12.2 and I could not reproduce the issue even after trying 25-30 times. 

Please check the browser's console for error message if it happens next time. It might help us to reproduce the issue, if the console shows any error. Closing the issue now. Please feel free message in the same thread if you capture any error in the console.

**Closed by ShahanaFarooqui** 2022-04-18 17:06 UTC
Labels: bug, Eclair
