### ISSUE TITLE
No Fee Limit not working

### ISSUE THREAD

**Issue by varunagym** [Ride-The-Lightning/RTL#913] opened 2021-12-21 04:01 UTC
**Describe the bug**
Payments do no work with "No Fee Limit" option. Works fine with fixed or percentage.

**Screenshots**
<img width="701" alt="Screen Shot 2021-12-21 at 10 44 11 AM" src="https://user-images.githubusercontent.com/96417561/146868050-509ce93e-b7cf-4464-ad73-0f36a57e11e4.png">

**Your environment**
* Version of `RTL`: 0.11.2-beta
* Version of `lnd`:  0.14.1-beta
* Version of `bitcoind`: 220000
* Server Operating system: Linux [redacted] 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
* Browser & browser version: Brave V1.33.106
* Client Operating system: Darwin [redacted] 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64

**Additional context**
I'm running BTCPayServer v1.3.7.0

**Comment by ShahanaFarooqui** [comment] 2021-12-21 04:24
Duplicate of #867 and closing with PR #880.

**Closed by ShahanaFarooqui** 2021-12-21 04:24 UTC
Labels: bug, duplicate, LND
