### ISSUE TITLE
Unable to update channel fee policies

### ISSUE THREAD

**Issue by AaronAlexiuc** [Ride-The-Lightning/RTL#767] opened 2021-08-23 02:21 UTC
Unable to update channel fee policies when node updated to LND 0.13.1

**To Reproduce**
1. Go to 'Peer/Channels'
2. Click on 'Actions'
3. Click on 'Update Fee Policy' then 'Update Channel'
4. RTL loading spinner for about 2 minutes and then this error -

![image](https://user-images.githubusercontent.com/59424815/130380436-b955d416-611f-4559-a13a-2d8758b9ccc9.png)

RTL version - 0.10.0-beta
LND version - 0.13.1-beta
BTCPayserver - v1.2.1.0

Issue has only started happening once LND upgraded to v0.13.1
LND node on 0.12.1 still works fine.

**Comment by ShahanaFarooqui** [comment] 2021-08-23 10:59
@AaronAlexiuc, thanks for opening the issue. I am unable to reproduce it at my end with above mentioned versions. 

However, we had to re-adjust unlock and initial loading logic for RTL after upgrading LND to 13.1. 

Hope the [commit](https://github.com/Ride-The-Lightning/RTL/commit/24b006519fe20631c205b1a323afa4628ef9cebb) will fix your issue as well. It will be release with RTL v0.11.1. Please feel free to comment again if it persists after RTL's upgrade too. Closing the issue for now.

**Closed by ShahanaFarooqui** 2021-08-23 10:59 UTC
Labels: bug, LND

**Comment by saubyk** [comment] 2021-08-28 15:17
@ShahanaFarooqui assuming this fix is backwards compatible?
