### ISSUE TITLE
Unable to create a RTL-Config.json file with a pre-populated "multiPassHashed"

### ISSUE THREAD

**Issue by miketwenty1** [Ride-The-Lightning/RTL#911] opened 2021-12-18 18:07 UTC
**Describe the bug**
It seems that creating a RTL-Config.json file with a pre-populated "multiPassHashed" results in not being able to use the password. I verified the multiPassHashed are unsalted sha256 hashes of the password. 

The usecase here for this to work is setting up an automated password where you know the hash ahead of time and don't want the password secret in your config template. 

I'm unsure if this is a feature request or bug, but it seems you HAVE to utilize the "multiPass" field in order to have a password properly set in RTL.

**Comment by ShahanaFarooqui** [comment] 2022-02-12 01:24
@miketwenty1 I am unable to reproduce it. We can directly setup the config file with `multiPassHashed` and RTL will just skip the step where it updates `multiPass` to `multiPassHashed`.

**Comment by ShahanaFarooqui** [comment] 2022-02-27 02:27
@miketwenty1 I am unable to reproduce the issue. Closing this now, but please feel free to comment if it persists at your end.

**Closed by ShahanaFarooqui** 2022-02-27 02:27 UTC
