### ISSUE TITLE
Missing Action menu

### ISSUE THREAD

**Issue by ramahama** [Ride-The-Lightning/RTL#1172] opened 2023-01-11 16:07 UTC
Action menu for opened channels list is missing after update to Release v0.13.4-beta. Previously was on the marked area on the screenshot picture.
Screenshot attached.
![RTL_Issue](https://user-images.githubusercontent.com/122465922/211856128-9911763f-cb41-449e-aad9-464133de9ff1.jpg)

I'm running mynode v.	0.3.08

**Comment by ShahanaFarooqui** [comment] 2023-01-13 05:30
I am unable to reproduce this error on my end. Could you confirm your NodeJS version & browser?

**Comment by tehelsper** [comment] 2023-01-13 23:52
Do you just need to scroll to the right? I'd expect the dropdown to be a bit further over to the side.

**Comment by saubyk** [comment] 2023-01-14 00:00
> Do you just need to scroll to the right? I'd expect the dropdown to be a bit further over to the side.

Actually yes. We failed to notice that lol 😅 

@ramahama what you highlighted on the attached screen shot is not where the actions button is. You need to scroll to the right.

**Comment by ShahanaFarooqui** [comment] 2023-01-14 02:26
@ramahama Either scroll to right to see Actions menu or configure your settings to show lesser number of columns to avoid scrolling.

Closing the issue now. Thanks.

**Closed by ShahanaFarooqui** 2023-01-14 02:26 UTC
