### ISSUE TITLE
eclair v0.8.0 uses default values for API call paramters from/to

### ISSUE THREAD

**Issue by DerEwige** [Ride-The-Lightning/RTL#1143] opened 2022-12-06 11:55 UTC
Since the eclair v0.8.0 release all the APIs that use "from" and "to" use default values for those parameters if not set.
Because of this RTL only fetches the data from the last 24 hours.

**To Reproduce**
Connect RTL 0.13.2 to eclair 0.8.0 and check any lightning panel.
You only see the last 24 hours

![image](https://user-images.githubusercontent.com/6146383/205905114-cc4e3ce6-ebb0-4ca7-8c8b-c5977c8e0508.png)

**Your environment**
* Version of `RTL` 0.13.2
* Version of `leclair' 0.8.0

**Comment by ShahanaFarooqui** [comment] 2022-12-15 22:10
@DerEwige Thank you for the issue and finding the root cause also :). Bug has been fixed and merged in release 0.13.3 branch. Hopefully we will release it by this weekend.

Closing with PR #1149.

**Closed by ShahanaFarooqui** 2022-12-15 22:10 UTC
Labels: bug, Eclair
