### ISSUE TITLE
UI Modal Window while changing nodes or closing channels.

### ISSUE THREAD

**Issue by iangregsondev** [Ride-The-Lightning/RTL#649] opened 2021-04-12 13:26 UTC
**Describe the bug**

**To Reproduce**

I have 2 nodes setup, change from 1 node to another just displays "initializing node data" and never returns, I have to refresh the screen.

Force closing a channel, does the same... shows the progress on the UI but never returns...

In both cases I checked the logs and also the browser network window and I don't see anything strange..

If I can offer more info then let me know and I will gather it up.

Thanks.

**Screenshots**

![image](https://user-images.githubusercontent.com/2370364/114401392-2bb21e00-9ba3-11eb-8a90-0969832c633c.png)

![image](https://user-images.githubusercontent.com/2370364/114401406-2ead0e80-9ba3-11eb-90a8-6f2b222c71fd.png)

**Your environment**
* Version of `RTL` shahanafarooqui/rtl:0.10.1
* Version of `lnd` lightninglabs/lnd:v0.12.1-beta
* Version of `btcd`, `bitcoind`, or other backend: 0.21.0

**Comment by iangregsondev** [comment] 2021-04-12 13:27
Should have mentioned, its on Testnet.

**Comment by ShahanaFarooqui** [comment] 2021-04-12 22:54
@iangregsondev Thanks for the issue and details.

1: Regarding channel closing: The API to close the channel is synchronous and the UI waits for its response for 10 minutes before triggering the timeout response. 

2: Regarding node change: Can you please check the `Console` tab for errors. If the logs file and network are not showing any error, most likes it should show up in the console. For example:

![image](https://user-images.githubusercontent.com/23240721/114472459-3fb84880-9bc0-11eb-95d7-79ecf8e37ad3.png)

**Comment by iangregsondev** [comment] 2021-04-13 07:10
Hi, The problem happens in both chrome and safari. I thought I would check, just in case.

I am afraid there are no errors in the console.

There is 1 error, but that happens previously to changing the node... from the drop-down

![image](https://user-images.githubusercontent.com/2370364/114511212-e8ee5580-9c37-11eb-96f5-69184a57cb22.png)

**Comment by iangregsondev** [comment] 2021-04-13 13:51
I have moved away from using the same RTL for 2 separate nodes, as I always had to change context and once I changed 1 window to the other node - the other node would also change.

So I set up 2 x RTLs. Made better sense.

So this error doesn't apply to me anymore, but of course, I believe its still there :-)

You can feel free to close this for me.

**Comment by ShahanaFarooqui** [comment] 2021-04-14 19:41
I am unable to reproduce the error at my end. Closing the issue for now. Please feel free to reopen if it persists.

**Closed by ShahanaFarooqui** 2021-04-14 19:41 UTC
Labels: troubleshooting
