### ISSUE TITLE
Backup download error

### ISSUE THREAD

**Issue by bota87** [Ride-The-Lightning/RTL#471] opened 2020-09-20 13:04 UTC
I can't download the backup file for all the channels, it works for one channel at time.

Go to Lightning\Backup and click on Download Backup, the following error appear
`Reading File Failed!
Error Code
-2
Error Message
ENOENT
API URL
./api/conf/file?channel=ALL`
* Version of `RTL` 0.9

I think the problem is releted to the case sensitive file name (channel-all.bak, when the api look for channel-ALL.bak). I have renamed the file with the upper case, after that the download works

**Comment by ShahanaFarooqui** [comment] 2020-09-23 00:56
We are unable to reproduce the issue with File name's case sensitivity. Although, we get the same error message when the file does not exist in the folder. So we updated it with clearer error message. 

Please ensure that the file exists in the folder before attempting to download it. Closing the issue with PR #479.

**Closed by ShahanaFarooqui** 2020-09-23 00:56 UTC
Labels: bug
