### ISSUE TITLE
Channel Circular rebalancing progress info not shown

### ISSUE THREAD

**Issue by yik77** [Ride-The-Lightning/RTL#751] opened 2021-08-14 18:17 UTC
**Is your feature request related to a problem? Please describe.**
When circular rebalance is carried out, estimation does not show what is the route. When you carry out the rebalance, there is no info on progress, no status, no feedback to user other than it failed after the time. Even when you expand arrow to see progress, nothing is shown. 

**Describe the solution you'd like**
Shown some diagnostics. there must be something that is output of circular rebalance in progress. 

**Describe alternatives you've considered**
Trial and error for multiple variants of fees, or peers. It is really frustrating. 

**Additional context**
Overall, it would be nice if more stuff is shown, like when estimating, why is it nearly always wrong/unreliable? 
Failed circular rebalance invoices are stuck there forever. Not great.

**Comment by saubyk** [comment] 2021-08-15 17:02
Hi @yik77 
The fee estimation logic uses the `queryroutes` API of LND, which gives a poor estimate of the routing fee. It's important to note that it is actually impossible to accurately predict routing fee estimates, because of significant number of unknowns on the network graph. And, these unknowns are built by design on the protocol to protect user privacy.

We are planning to remove the fee estimate, so that you are forced to put in the fee amounts you're comfortable to pay to execute the rebalance.
https://github.com/Ride-The-Lightning/RTL/issues/739

Also note that there are variety of reasons for circular balances to fail and success is not a guaranteed outcome. It may fail if:
- your node is not connected with well funded peers, who can complete the circuit for you
- you're trying to rebalance an amount, much larger than what your peer channels can support
- you're not paying enough routing fee to complete the payment circuit

This being said, you can do the following to improve your chances of success:
- Do not use the fee estimate suggested by RTL
- Start with the smaller amounts, so that you get an idea of how well connected/funded your peers are to support your payments
- Keep bidding up the fee amount you can pay to route

If after doing all the above, you're not able to route payments, the best bet would be to open channels with new peers (incoming and outgoing), who can route the payments better back to you.

I am closing this ticket, as there is nothing we can do on this particular item and will address removal of fee estimates with the linked issue. Hope this is helpful. Thanks.

**Closed by saubyk** 2021-08-15 17:02 UTC
