### ISSUE TITLE
Wrong condition

### ISSUE THREAD

**Issue by bitbandi** [Ride-The-Lightning/RTL#866] opened 2021-11-23 01:03 UTC
**Describe the bug**
At sending payment feelimittype condition is wrong.

Here: https://github.com/Ride-The-Lightning/RTL/blob/master/src/app/lnd/store/lnd.effects.ts#L670

Because FEE_LIMIT_TYPES is an object with 3 fields: https://github.com/Ride-The-Lightning/RTL/blob/master/src/app/shared/services/consts-enums-functions.ts#L38-L42
the payload.feeLimitType is built here: https://github.com/Ride-The-Lightning/RTL/blob/master/src/app/lnd/transactions/send-payment-modal/send-payment.component.ts#L137, and L139

Three field object compared to a two field object, always false.

Anyway here is only a single value passed to feeLimitType: https://github.com/Ride-The-Lightning/RTL/blob/master/src/app/lnd/peers-channels/channels/channel-rebalance-modal/channel-rebalance.component.ts#L214

Possible fix: always use the id value from FEE_LIMIT_TYPES.

**Comment by ShahanaFarooqui** [comment] 2021-11-23 02:15
@bitbandi Thank you for proof reading the code but the condition in lnd.effects is comparing two objects with 3 key values. The variable `FEE_LIMIT_TYPES[0]` returns zeroth value of the array which is the whole object as ` { id: 'none', name: 'No Fee Limit', placeholder: 'No Limit' }`. 

And this condition simply states to NOT to send fee limit type and value to the request, if the selected fee limit is `none`. The POST request will only have `{fixed: <numeric value>}` or `{percent: <numeric value>}` in the request. If the FEE_LIMIT_TYPE is selected as `none`, then no fee limit info should be passed. 

Please fee free to refer to the [documentation](https://github.com/Ride-The-Lightning/RTL/blob/master/docs/Contributing.md#code) to be able to setup your own development environment to be able to debug them more efficiently. Closing the issue now. Thanks.

**Closed by ShahanaFarooqui** 2021-11-23 02:15 UTC

**Comment by bitbandi** [comment] 2021-11-23 10:03
i had an error, but i cannot repoduct anymore, i fixed in my code.... :)

in send-payment.component.ts#L137, the object has only two fields: id and name, and the whole object is compared to "3 key object". the expression is always true.

**Comment by ShahanaFarooqui** [comment] 2021-11-25 01:46
@bitbandi Thanks again for debugging the issue. Indeed this was the root cause. Fixed the bug by passing the id from the components.
