### ISSUE TITLE
Unconfirmed on chain balance after force close

### ISSUE THREAD

**Issue by Squinck** [Ride-The-Lightning/RTL#1286] opened 2023-09-15 06:25 UTC
Hi all,
I tried opening a channel of 1.000.000 sats but I used to few fees so it didn't get through. 
After 5 weeks of this pending channel I got advised to do a force close. That seemed to work as the channel moved to pending close.
After a few days this transaction showed up in my Raspiblitz dashboard saying. 0:sweep. But there is another transaction of 147 Sats which I do not understand.
Anyway. RTL is telling me that there are still 994,798 SATS unconfirmed.
Some people I asked for help tell me to use bitcoin-cli:
bitcoin-cli sendrawtransaction "[raw_tx_hash]" 
Regarding this transaction:
f7193dd75f1bbd500b7d72f6a959fff743ef1822584067d8c008619d5be7b010
Doing this I would be able to raise te fees, but I don't have any idea how.

Furthermore my Raspiblitz is stalling/hanging
Could this be related to the issue I have with the closing channel?
![RTLdash](https://github.com/Ride-The-Lightning/RTL/assets/145057781/e66b1c5b-933a-45ef-b250-1d2dd968d29b)
![screenclosed](https://github.com/Ride-The-Lightning/RTL/assets/145057781/aaa3b2ec-8039-4f93-a22c-904f2de3d0b4)
![Raspdash](https://github.com/Ride-The-Lightning/RTL/assets/145057781/87001603-01d6-41bf-8421-ead970aa9615)

**Comment by saubyk** [comment] 2023-09-15 18:17
Hi @Squinck are you running a pruned Bitcoin node?

**Comment by saubyk** [comment] 2023-09-15 18:19
Also, have you tried restarting your node?

**Comment by Squinck** [comment] 2023-09-16 21:58
> Hi @Squinck are you running a pruned Bitcoin node?

No I run Raspiblitz on a Raspberry Pi with ssd drive which contains the whole blockchain.... At least as far as I know.

**Comment by Squinck** [comment] 2023-09-16 21:58
> Also, have you tried restarting your node?

Yes a few times

**Comment by saubyk** [comment] 2023-09-17 14:39
So there is an inconsistency in what you described so far:
You said that your open channel transaction didn't get through, because you used too low a fee, but then you were also able to force close? You can only force close a channel which has been open, not a pending open channel

Can you share the transaction id of the channel opening transaction? And also the transaction id of the pending transaction which is showing up as unconfirmed in RTL?

Most likely you'll have to rescan your LND wallet to get the funds to show up as confirmed, as I don't believe your UTXOs have been spent at all.

**Comment by Squinck** [comment] 2023-09-18 14:13
The channel was listed at the pending channels. I was advised to run this lncli closechannel --force funding_txid what made the channel move to pending close.

**Comment by Squinck** [comment] 2023-09-18 14:30
"tx_hash": "f7193dd75f1bbd500b7d72f6a959fff743ef1822584067d8c008619d5be7b010",
  "num_confirmations": 0

That's the unconfirmed transaction

**Comment by Squinck** [comment] 2023-09-18 14:44
Is this what you needed? I don't know where to find the channel ID of the opening channel.

Thank you for your help @saubyk

**Comment by Squinck** [comment] 2023-09-18 15:09
After another reboot, thing look okay again??
I can see my balance and also the Raspberry interface is not hanging anymore

**Comment by saubyk** [comment] 2023-09-18 17:32
> I think I found it. 6757195e87b2f62e16c1bbd8ad011831e2f8a675df7bcc8410ee37b6fac072d1
> 
> Is the transaction hash of the opening channel

So give this information, I see the below happening in your case:

Both your channel opening and close transactions were confirmed, you can see that here:
https://mempool.space/address/bc1q3x0wt2xfx6zgdwz7ynqq9az7nwcdhlxmut4tq4gdgs9tep9elmqs53h4lt
Channel opening tx id: 6757195e87b2f62e16c1bbd8ad011831e2f8a675df7bcc8410ee37b6fac0
72d1
Channel closing tx id: 3514ed03e4863f3df0faa550a3d2833d3cf2f861a033275e1ddef24e0af3
a33f

Then the from the channel closing transaction there was a sweep transaction created to move the funds from force close to wallet spendable output. That transaction is confirmed as well, which is this:
https://mempool.space/tx/262b208d15db05d49e587e00b487b9c7906adad051c6dfce4cc9d151782fc282
From this transaction we can see that your utxo from force close for the amount 996530 sats was swept to the amount 994651 sats.
So finally your node should have a confirmed output of 994651 sats after all of the above.
Which you should be able to track on the onchain page of RTL.

In the end you have all your funds accounted for. Closing this issue now.

**Closed by saubyk** 2023-09-18 17:32 UTC
Labels: troubleshooting
