### ISSUE TITLE
Connecting to new peer throws error 'Already added'

### ISSUE THREAD

**Issue by SteliosRammos** [Ride-The-Lightning/RTL#207] opened 2019-11-27 02:05 UTC
**Describe the bug**
Trying to connect to a new peer throws an error "Already connected to peer". Although the peer was not previously connected and the command successfully adds the new peer. I verify the connection by running **lncli listpeers** in the command line. None of the peers I'm connected to show in the list, the list of peers is empty.

**To Reproduce**
1. Go to 'Peers'
2. Enter node pubkey
2. Click on 'Connect'
3. 'Adding peer' will load for a while, but the command line already shows the error
4. See error on UI

**Your environment**
* version of `lnd`: lnd version 0.8.0-beta commit=v0.8.0-beta-208-gd4d8b03d5b82d626728696cf18eb66029a0f2cb1
* operating system: Ubuntu 18.04.3 LTS
* version of `btcd`: Bitcoin Core Daemon version v0.18.1
* Running remotely on MacOS 10.15.2 Beta

**Command Line Error**
Unhandled rejection StatusCodeError: 500 - {"error":"already connected to peer: 027cd974e47086291bb8a5b0160a889c738f2712a703b8ea939985fd16f3aae67e@35.237.192.216:9735","message":"already connected to peer: 027cd974e47086291bb8a5b0160a889c738f2712a703b8ea939985fd16f3aae67e@35.237.192.216:9735","code":2}
    at new StatusCodeError (/home/stelios/RTL/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/home/stelios/RTL/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/home/stelios/RTL/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/home/stelios/RTL/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/stelios/RTL/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/stelios/RTL/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by ShahanaFarooqui** [comment] 2019-12-29 23:45
@SteliosRammos We were unable to reproduce the error at our end. Please share RTL's logs file for more details.

**Comment by Ride-The-Lightning** [comment] 2020-01-17 20:47
We are closing the issue assuming that it is resolved.

**Closed by Ride-The-Lightning** 2020-01-17 20:47 UTC
Labels: Troubleshooting
