### ISSUE TITLE
Circular Rebalance Infographics

### ISSUE THREAD

**Issue by ShahanaFarooqui** [Ride-The-Lightning/RTL#289] opened 2020-03-25 17:36 UTC
https://github.com/Ride-The-Lightning/RTL-Design/pull/46: PR blocked for Suheb's input.

**Comment by saubyk** [comment] 2021-06-21 02:42
Duplicate of https://github.com/Ride-The-Lightning/RTL/issues/450

**Closed by saubyk** 2021-06-21 02:42 UTC
Labels: enhancement
