### ISSUE TITLE
[eclair]  private channels are shown as public in RTL

### ISSUE THREAD

**Issue by viaj3ro** [Ride-The-Lightning/RTL#1092] opened 2022-09-06 09:27 UTC
for some reason RTL ignores the `announceChannel` flag and marks channels as public, even if the flag is set to `false`

**Comment by ShahanaFarooqui** [comment] 2022-09-10 01:59
Closing with PR #1094

**Closed by ShahanaFarooqui** 2022-09-10 01:59 UTC
Labels: bug, Eclair

**Comment by ShahanaFarooqui** [comment] 2022-09-10 02:02
@viaj3ro Thank you for opening the issue. Root cause for the bug was change in channel's response signature from Eclair.
