### ISSUE TITLE
Rename Old Database Error: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

### ISSUE THREAD

**Issue by 1ma** [Ride-The-Lightning/RTL#1138] opened 2022-11-27 11:15 UTC
**Describe the bug**

Not really a showstopper, but I've noticed that since I updated to RTL 0.13.2 I get this error in the log each time I log into RTL:

```
ERROR: Database => Rename Old Database Error: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
```

**To Reproduce**
1. Update RTL to 0.13.2
2. On a terminal, run `$ journalctl -f -u rtl.service` to tail the logs
3. Log into RTL

**Your environment**
* Version of `RTL`: v0.13.2
* Version of `lnd`/`core lightning`/`eclair`: v0.12.1 (Core Lightning) and v0.9.0 (c-lightning-REST)
* Version of `btcd`, `bitcoind`, or other backend: Bitcoin Core v23.0
* Browser & browser version: LibreWolf v107.0-1
* Operating system (`uname -a` on *Nix): Ubuntu Server 22.04, Linux 5.15.0-53-generic x86_64

**Comment by ShahanaFarooqui** [comment] 2022-11-27 15:12
Do you have any data in your existing db file? You can check that in rtl/database folder.

**Comment by ShahanaFarooqui** [comment] 2022-11-27 16:24
@1ma Thank you for raising the issue. I was able to reproduce this issue on my end. 

The root cause of the issue is incorrect data format in the db file. But this error doesn't effect anything and can either be ignored or fixed by deleting all files in the rtl/database folder starting with `rtldb-node`, eg. rtldb-node-1.json.

**Comment by 1ma** [comment] 2022-11-27 16:24
```bash
rtl@node:/var/www/RTL/database$ tree
.
├── node-1
│   ├── rtldb-CLN-Offers.json
│   └── rtldb-CLN-PageSettings.json
└── rtldb-node-1.json

1 directory, 3 files
rtl@node:/var/www/RTL/database$ cat rtldb-node-1.json
{}
rtl@node:/var/www/RTL/database$ cat node-1/rtldb-CLN-Offers.json
[]
rtl@node:/var/www/RTL/database$ cat node-1/rtldb-CLN-PageSettings.json
[]
```

**Comment by ShahanaFarooqui** [comment] 2022-11-27 16:26
@1ma You can delete `rtldb-node-1.json` and the error will disappear. RTL has already created node-1/rtldb-CLN-Offers.json instead of renaming your old file. So deleting the old one is safe.

**Comment by ShahanaFarooqui** [comment] 2022-11-27 16:28
Added the null check for future releases. Closing the issue now as no other action is required.

**Comment by 1ma** [comment] 2022-11-27 16:29
Thanks man, it worked.

**Closed by ShahanaFarooqui** 2022-11-27 16:28 UTC
