### ISSUE TITLE
Error message when paying invoice without setting a fee limit

### ISSUE THREAD

**Issue by bitcoinheiro** [Ride-The-Lightning/RTL#867] opened 2021-11-23 15:48 UTC
**Describe the bug**
Error message when paying invoice without setting a fee limit

**To Reproduce**
Try to pay a invoice within RTL.
See error

**Screenshots**
![image](https://user-images.githubusercontent.com/50273260/143056590-74dfe00a-ed8e-4112-acef-97c41df6dcac.png)

**Your environment**
Latest BTCPayServer running on VPS
Other user from Umbrel reported same problem

**Comment by ShahanaFarooqui** [comment] 2021-11-23 20:14
Due to LND update to 0.14

**Comment by acantril** [comment] 2021-11-23 21:08
confirmed, same issue lnd 0.14

**Comment by jaonoctus** [comment] 2021-11-23 22:01
+1, had the same issue

**Comment by bitbandi** [comment] 2021-11-24 07:33
already reported the issue: #866

**Comment by ShahanaFarooqui** [comment] 2021-11-25 01:51
Closing with PR #880.

**Closed by ShahanaFarooqui** 2021-11-25 01:51 UTC
Labels: LND, version compatibility
