### ISSUE TITLE
the 0.12.2 version is missing some key info in the dashboard, when running with eclair

### ISSUE THREAD

**Issue by viaj3ro** [Ride-The-Lightning/RTL#975] opened 2022-03-12 13:29 UTC
weekly and daily is missing while monthly is shown. Tx show up in routing and reports though.

![image](https://user-images.githubusercontent.com/42124006/158019781-85a2bd8f-e50f-45e9-a1f3-1371c41ad6a4.png)

**Comment by viaj3ro** [comment] 2022-03-12 14:13
There seem to be some issues elsewhere as well:

![image](https://user-images.githubusercontent.com/42124006/158021334-1b6042df-08b4-4644-af02-c6911b1a775f.png)

**Comment by ShahanaFarooqui** [comment] 2022-04-15 15:24
@viaj3ro Thanks for raising the issue. Fee calculation on the dashboard has been fixed but i could not reproduce the issue at forwarding history. Closing the issue with PR #995.

**Closed by ShahanaFarooqui** 2022-04-15 15:24 UTC
Labels: bug, Eclair
