### ISSUE TITLE
I can't see my utxos

### ISSUE THREAD

**Issue by elchula76** [Ride-The-Lightning/RTL#852] opened 2021-11-06 18:15 UTC
**Describe the bug**

I have the following behavior: 
[2021-11-06T15:50:00.864Z] ERROR: Wallet => List UTXOs Error: {"name":"StatusCodeError","statusCode":404,"message":"404 - {\"code\":5,\"message\":\"Not Found\",\"details\":[]}","error":{"code":5,"message":"Not Found","details":[]},"options":{"url":"https://localhost:8080/v2/wallet/utxos?max_confs=708493","rejectUnauthorized":false,"json":true,"headers":{},"method":"POST","qs":{},"simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false},"response":{"statusCode":404,"body":{"code":5,"message":"Not Found","details":[]},"headers":{"content-type":"application/json","date":"Sat, 06 Nov 2021 15:50:00 GMT","content-length":"47","connection":"close"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"localhost:8080","port":"8080","hostname":"localhost","hash":null,"search":"?max_confs=708493","query":"max_confs=708493","pathname":"/v2/wallet/utxos","path":"/v2/wallet/utxos?max_confs=708493","href":"https://localhost:8080/v2/wallet/utxos?max_confs=708493"},"method":"POST","headers":{"accept":"application/json","content-length":0}}}}

**Screenshots**

![image](https://user-images.githubusercontent.com/90146134/140619506-d2c4adf4-4ccd-4f6f-b3e4-2b3834a735af.png)

**Your environment**
* Version of `RTL` versión 0.11.2.-beta
* Version of `lnd`  0.13.99-beta
* bitcoind 0.21.1
* Browser & browser version: The same issue at firefox and brave
* Operating system (`uname -a` on *Nix) Ubuntu 20.04.3 LTS
* any other relevant environment details: Iḿ using at lnd.conf restlisten=127.0.0.1:8080 to connect with btcpayserver

Thanks

**Comment by saubyk** [comment] 2021-11-10 23:14
Hi @elchula76 this appears to be happening with the latest LND release candidate (i.e. 0.14). Although I am not sure what version of LND is 0.13.99?

Regardless, this will be addressed in the next release, after LND release its 0.14 release. Thanks.

**Comment by elchula76** [comment] 2021-11-11 11:38
Good morning, yes thats it, is the 0.13.99.

Thanks

**Comment by bitbandi** [comment] 2021-11-20 20:44
0.14-beta is released: https://github.com/lightningnetwork/lnd/releases/tag/v0.14.0-beta

**Comment by ShahanaFarooqui** [comment] 2021-11-23 18:21
No further action required. Closing the issue now. Thanks.

**Comment by bitbandi** [comment] 2021-11-23 18:23
???
the issue is still exists :(

**Comment by acantril** [comment] 2021-11-23 21:22
confirmed still occurring on 0.14

**Comment by ShahanaFarooqui** [comment] 2021-11-25 02:57
Opened an issue with LND: https://github.com/lightningnetwork/lnd/issues/6028

**Comment by ShahanaFarooqui** [comment] 2021-11-25 14:35
Closing with PR #882

**Closed by ShahanaFarooqui** 2021-11-25 14:35 UTC
Labels: bug, LND, version compatibility
