### ISSUE TITLE
Circular Rebalance Stuck

### ISSUE THREAD

**Issue by cailenmusselman** [Ride-The-Lightning/RTL#1173] opened 2023-01-15 15:18 UTC
**Describe the bug**
When attempting to do a Circular Rebalance, I occasionally get the "Invoice generated ✔" and "Payment successful ✔" messages.  However, the channel balances don't update. And when going to the Transactions -> Invoices tab I can see the invoices are there, but haven't been completed, despite the "Payment successful ✔" message I received.
When I click to expand the "Invoice generated" box and the "Payment successful" box nothing happens.

**To Reproduce**
From what I'm seeing, I'm able to reproduce the issue on *any* invalid rebalance. Sometimes the "Payment successful" message shows up almost instantaneously. I've yet to see a "Payment failed" message, just stuck invoices.

**Your environment**
* Version of `RTL`: **0.13.2-beta**
* Version of `lnd`/`core lightning`/`eclair`: **LND 0.15.5-beta**
* Version of `btcd`, `bitcoind`, or other backend: **Bitcoin Core 24.0.1**
* Browser & browser version:
* Operating system (`uname -a` on *Nix): **Umbrel 0.5.2**
* any other relevant environment details

**Comment by saubyk** [comment] 2023-01-21 00:03
Hi @cailenmusselman I tried it on my node, wasn't able to reproduce the issue for any of the attempts I tried.
The success of circular rebalancing is dependent on many factors e.g.
- How well connected your peers are
- The fee limit you're setting on the rebalance attempts

Have you tried increasing the fee limit on the failed cases?

**Comment by cailenmusselman** [comment] 2023-02-15 02:26
Hey @saubyk, sorry for the late response here. Totally understand that circular rebalancing will fail for a myriad of reasons, BUT the issue I'm reporting is that I'm still getting the "Invoice generated ✔" and "Payment successful ✔" even when the circular rebalance definitely failed. Sometimes the messages pop up almost instantly, so I think it's just a UI bug.

Will try and reproduce the next time I go to rebalance. But no hard feelings if you want to close the issue.

**Comment by saubyk** [comment] 2023-02-15 02:58
We can keep the issue open for some time, in case anyone reports the same.

**Comment by djmuhlestein** [comment] 2023-02-25 15:51
I can reproduce this easily.  The common situation is a no_route error on the LND side.  Another is if the fee is too low.  In either case, the payment confirmation says payment successful except the payment was not successful.

In addition, if it doesn't immediately says successful but it is attempting to make the payment and waiting a while, I've seen a timeout occur and in that case, the reroute dialog also jumps to the successful status. 

In both cases I believe it should tell you there was an error instead.

**Comment by stupleb** [comment] 2023-04-10 08:14
This has been happening for me since 0.13.3 at least until 0.13.6 I'm using now, two separate nodes. Circular rebalance will appear to have succeeded with "Payment Success" on the UI, but in reality it didn't. It will have either looked for a route and failed (you can tell because a few seconds pass) or it will fail instantly with a "Payment Success".

In console it shows:

`ERROR TypeError: t.paymentStatus.payment_route is undefined`

**Comment by ShahanaFarooqui** [comment] 2023-04-20 19:38
Response signature of send payment API changed. New response is added with the key `result` now. Fixed with PR #1222.

**Closed by ShahanaFarooqui** 2023-04-20 19:38 UTC
Labels: bug, LND
