### ISSUE TITLE
Invoices are not listed after refreshing page

### ISSUE THREAD

**Issue by TheeHandwoven** [Ride-The-Lightning/RTL#682] opened 2021-05-19 14:32 UTC
Go to the Transactions->Invoices page. For this error to happen you need to have at least a single invoice.

Now refresh the page. It will now say "No invoices available", so you have to change tabs back and forth to restore them to the view.

**Comment by ShahanaFarooqui** [comment] 2021-06-10 23:48
I am unable to reproduce the error with 'Release-0.11.0' branch. Please wait till the next release or provide more details like versions and browsers. Closing the issue now. Please feel free to reopen if issue exists with v0.11.0.

**Closed by ShahanaFarooqui** 2021-06-10 23:48 UTC
Labels: troubleshooting
