### ISSUE TITLE
/cln/connections/channels/open returns "Unknown Error"

### ISSUE THREAD

**Issue by g00g1** [Ride-The-Lightning/RTL#1288] opened 2023-09-16 10:29 UTC
**Describe the bug**
I have installed BTCPayServer with Tor support, CLN and RTL, have bought incoming liquidity from yalls.org and some time later (after transition from channel pending state) I started to observe this issue as can be seen below at screenshots section

**To Reproduce**
Steps to reproduce the behavior are described within bug summary

**Screenshots**

<details><summary>Lightning > Peers/Channels tab</summary>
<p>
<img src="https://github.com/Ride-The-Lightning/RTL/assets/91201021/bb662ca5-e40c-4657-ad23-dfee89677f48"/>
</p>
</details> 

**Your environment**
* Version of `RTL`: `0.14.0-beta`
* Version of `core lightning`: `basedon-v23.08`
* Version of `bitcoind`: `v25.0.0`
* Browser & browser version: `Firefox 102.15.0esr`
* Operating system (`uname -a` on *Nix): `Linux btcpayserver 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64 GNU/Linux`

* any other relevant environment details

**Additional context**
After posting this issue the bug disappeared and now I can see my channels... Don't know where to dig further for details on this issue. Please let me know if you need any logs relevant.

**Comment by TowyTowy** [comment] 2023-09-21 18:58
I just got this too...

**Comment by NicolasDorier** [comment] 2023-09-22 08:22
It is possible that core ligthtning needed some migration which took time, during which the Lightning REST could not connect to it.

Did it happened again?

**Comment by g00g1** [comment] 2023-09-22 09:08
> Did it happened again?

No, I haven't interacted with my lightning node since then.

**Comment by ShahanaFarooqui** [comment] 2023-09-25 19:56
As per @g00g1's "After posting this issue the bug disappeared and now I can see my channels" and @TowyTowy's "It fixed itself today, it seems like it did when I opened yet another channel with it (Discord)" comment, the issue seems to be fixed and I cannot reproduce it.

No further action can be taken for now and I am closing the issue. Please feel free to post here with more details to reproduce it if it reappears.

**Closed by ShahanaFarooqui** 2023-09-25 19:56 UTC
