### ISSUE TITLE
Failing to send to main menu of dashboard after login

### ISSUE THREAD

**Issue by miketwenty1** [Ride-The-Lightning/RTL#910] opened 2021-12-17 05:23 UTC
**Describe the bug**
After you login, it fails to send ui to dashboard. There are no errors.

**To Reproduce**
1. put in password, click login
2. nothing happens, (you must now refresh the screen to get to the main dashboard).

**Screenshots**

**Your environment**
* Version of `RTL` 0.11.2
docker

**Comment by miketwenty1** [comment] 2021-12-17 06:20
this bug is very inconsistent.. not able to reproduce consistently

**Comment by kiwiidb** [comment] 2022-01-12 09:02
I am also experiencing this issue consistently on one of my RTL instances. No idea what's causing it, as I have multiple others that work fine.

**Comment by ShahanaFarooqui** [comment] 2022-01-12 12:45
Can you try after upgrading RTL to b0.12.0

**Comment by kiwiidb** [comment] 2022-01-13 09:40
Now it works after refreshing the page after clicking `Login`. I wasn't yet on 0.12.0 because I had some other issues with it earlier, forgot what it was unfortunately, but now it does seem to work.

**Comment by ShahanaFarooqui** [comment] 2022-02-12 01:26
Looks like it was the bug in older version and has been fixed now. I am unable to reproduce it with the latest release. Closing it now.

**Closed by ShahanaFarooqui** 2022-02-12 01:26 UTC
